const MEALS_DB = {
  breakfast: [
    { emoji: '🍚', name: 'Poha', description: 'Flattened rice tempered with mustard seeds, curry leaves, and peanuts', calories: 280, time: 15 },
    { emoji: '🍛', name: 'Upma', description: 'Semolina cooked with vegetables, mustard seeds, and curry leaves', calories: 300, time: 18 },
    { emoji: '🫓', name: 'Aloo Paratha', description: 'Whole wheat flatbread stuffed with spiced mashed potatoes', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Idli Sambar', description: 'Steamed rice cakes served with lentil sambar and coconut chutney', calories: 250, time: 25 },
    { emoji: '🥞', name: 'Masala Dosa', description: 'Crispy rice and lentil crepe filled with spiced potato filling', calories: 350, time: 25 },
    { emoji: '🍳', name: 'Anda Bhurji', description: 'Indian spiced scrambled eggs with onions, tomatoes, and green chilies', calories: 320, time: 15 },
    { emoji: '🫓', name: 'Gobi Paratha', description: 'Flatbread stuffed with spiced grated cauliflower and herbs', calories: 380, time: 30 },
    { emoji: '🥣', name: 'Daliya Porridge', description: 'Broken wheat porridge cooked with milk, sugar, and cardamom', calories: 260, time: 20 },
    { emoji: '🍛', name: 'Chole Bhature', description: 'Spiced chickpea curry served with deep-fried puffed bread', calories: 500, time: 40 },
    { emoji: '🥘', name: 'Puri Bhaji', description: 'Deep-fried puffed bread served with spiced potato curry', calories: 450, time: 30 },
    { emoji: '🫓', name: 'Methi Paratha', description: 'Fenugreek-flavored whole wheat flatbread with butter', calories: 350, time: 28 },
    { emoji: '🥞', name: 'Rava Dosa', description: 'Crispy semolina crepe with cumin and black pepper', calories: 280, time: 20 },
    { emoji: '🍚', name: 'Sabudana Khichdi', description: 'Tapioca pearls stir-fried with peanuts, potatoes, and cumin', calories: 320, time: 20 },
    { emoji: '🥘', name: 'Medu Vada', description: 'Crispy urad dal fritters served with sambar and coconut chutney', calories: 350, time: 30 },
    { emoji: '🍳', name: 'Egg Dosa', description: 'Thin rice crepe topped with a cracked egg and spices', calories: 300, time: 20 },
    { emoji: '🫓', name: 'Paneer Paratha', description: 'Flatbread stuffed with spiced crumbled paneer and herbs', calories: 420, time: 30 },
    { emoji: '🥣', name: 'Oats Upma', description: 'Rolled oats cooked with mustard seeds, vegetables, and peanuts', calories: 240, time: 15 },
    { emoji: '🍛', name: 'Misal Pav', description: 'Spicy sprouted moth beans curry served with bread rolls', calories: 400, time: 35 },
    { emoji: '🥘', name: 'Appam with Stew', description: 'Lacy rice pancake served with coconut vegetable stew', calories: 330, time: 35 },
    { emoji: '🫓', name: 'Mooli Paratha', description: 'Flatbread stuffed with spiced grated radish and green chilies', calories: 370, time: 30 },
    { emoji: '🍚', name: 'Pongal', description: 'Rice and moong dal cooked with black pepper, cumin, and ghee', calories: 310, time: 25 },
    { emoji: '🥞', name: 'Pesarattu', description: 'Green moong dal crepe served with ginger chutney', calories: 270, time: 20 },
    { emoji: '🍳', name: 'Omelette Pav', description: 'Masala omelette stuffed in a buttered bread roll', calories: 380, time: 15 },
    { emoji: '🥘', name: 'Uttapam', description: 'Thick rice pancake topped with onions, tomatoes, and green chilies', calories: 300, time: 20 },
    { emoji: '🫓', name: 'Pyaaz Kachori', description: 'Flaky pastry filled with spiced onion filling', calories: 400, time: 35 },
    { emoji: '🍛', name: 'Poha Jalebi', description: 'Flattened rice served alongside crispy sweet jalebi spirals', calories: 450, time: 25 },
    { emoji: '🥣', name: 'Ragi Porridge', description: 'Finger millet porridge with milk, jaggery, and cardamom', calories: 230, time: 15 },
    { emoji: '🍚', name: 'Batata Poha', description: 'Flattened rice with diced potatoes, turmeric, and lemon juice', calories: 290, time: 15 },
    { emoji: '🥞', name: 'Neer Dosa', description: 'Thin and delicate rice crepe served with coconut chutney', calories: 220, time: 15 },
    { emoji: '🫓', name: 'Sattu Paratha', description: 'Flatbread stuffed with roasted gram flour, onion, and spices', calories: 380, time: 28 },
    { emoji: '🍛', name: 'Pav Bhaji', description: 'Mashed vegetable curry served with toasted buttered bread rolls', calories: 480, time: 35 },
    { emoji: '🥘', name: 'Idiyappam', description: 'Steamed rice noodle nests served with coconut milk and sugar', calories: 260, time: 30 },
    { emoji: '🍳', name: 'Egg Paratha', description: 'Whole wheat flatbread layered with spiced egg mixture', calories: 390, time: 25 },
    { emoji: '🫓', name: 'Laccha Paratha', description: 'Multi-layered flaky whole wheat flatbread with ghee', calories: 350, time: 25 },
    { emoji: '🥣', name: 'Vermicelli Upma', description: 'Roasted vermicelli with peanuts, vegetables, and curry leaves', calories: 280, time: 18 },
    { emoji: '🍚', name: 'Indori Poha', description: 'Spiced flattened rice garnished with sev, pomegranate, and lime', calories: 300, time: 18 },
    { emoji: '🥞', name: 'Set Dosa', description: 'Soft and spongy dosa served in sets with chutney and sambar', calories: 310, time: 25 },
    { emoji: '🥘', name: 'Kanda Bhaji', description: 'Crispy onion fritters served with green chutney and chai', calories: 340, time: 25 },
    { emoji: '🫓', name: 'Bajra Roti with Gud', description: 'Millet flatbread served with jaggery and white butter', calories: 330, time: 20 },
    { emoji: '🍛', name: 'Aloo Tikki Chole', description: 'Crispy potato patties topped with chickpea curry and chutneys', calories: 450, time: 35 },
    { emoji: '🍳', name: 'Masala Omelette', description: 'Egg omelette with onions, green chilies, and coriander', calories: 280, time: 12 },
    { emoji: '🥣', name: 'Dalia Khichdi', description: 'Savory broken wheat cooked with moong dal and vegetables', calories: 270, time: 25 },
    { emoji: '🫓', name: 'Thepla', description: 'Gujarati spiced flatbread with fenugreek and yogurt', calories: 290, time: 20 },
    { emoji: '🥘', name: 'Puttu with Kadala', description: 'Steamed rice and coconut cylinders with black chickpea curry', calories: 370, time: 30 },
    { emoji: '🍚', name: 'Akki Roti', description: 'Karnataka rice flour flatbread with onions and coriander', calories: 260, time: 20 },
    { emoji: '🥞', name: 'Adai Dosa', description: 'Protein-rich mixed lentil crepe with jaggery and butter', calories: 320, time: 25 },
    { emoji: '🍛', name: 'Bedmi Puri Aloo', description: 'Urad dal stuffed fried bread with spiced potato curry', calories: 480, time: 35 },
    { emoji: '🫓', name: 'Makki di Roti', description: 'Cornmeal flatbread served with a dollop of white butter', calories: 300, time: 25 },
    { emoji: '🥘', name: 'Kozhukattai', description: 'Steamed rice dumplings filled with sweet coconut and jaggery', calories: 240, time: 35 },
    { emoji: '🍳', name: 'Egg Bhurji Pav', description: 'Spicy scrambled eggs served with buttered bread rolls', calories: 400, time: 15 },
    { emoji: '🥣', name: 'Sabudana Porridge', description: 'Sweet tapioca pearls cooked with milk and flavored with cardamom', calories: 250, time: 20 },
    { emoji: '🫓', name: 'Missi Roti', description: 'Spiced gram flour and wheat flatbread with onions', calories: 310, time: 22 },
    { emoji: '🍚', name: 'Chivda', description: 'Crunchy flattened rice mixture with peanuts, curry leaves, and spices', calories: 280, time: 15 },
    { emoji: '🥞', name: 'Onion Rava Dosa', description: 'Crispy semolina crepe topped with chopped onions and chilies', calories: 300, time: 20 },
    { emoji: '🥘', name: 'Paniyaram', description: 'Round fermented rice and lentil dumplings cooked in a mold', calories: 250, time: 25 },
    { emoji: '🍛', name: 'Kachori with Aloo', description: 'Fried pastry balls served with tangy potato curry', calories: 460, time: 35 },
    { emoji: '🫓', name: 'Litti Chokha', description: 'Baked wheat balls stuffed with sattu served with mashed vegetables', calories: 420, time: 45 },
    { emoji: '🍳', name: 'Boiled Egg Curry Toast', description: 'Spiced boiled egg curry served on toasted bread', calories: 340, time: 20 },
    { emoji: '🥣', name: 'Bajra Khichdi', description: 'Pearl millet porridge with ghee, buttermilk, and jaggery', calories: 310, time: 25 },
    { emoji: '🫓', name: 'Palak Paratha', description: 'Spinach-flavored whole wheat flatbread with butter', calories: 330, time: 28 },
    { emoji: '🥘', name: 'Maddur Vada', description: 'Crispy fried snack from Karnataka with onions, curry leaves, and rice flour', calories: 290, time: 25 },
    { emoji: '🍚', name: 'Beaten Rice Upma', description: 'Poha stir-fried with green peas, carrots, and tempered spices', calories: 270, time: 15 },
    { emoji: '🥞', name: 'Moong Dal Dosa', description: 'Crepe made from ground moong dal with ginger and green chili', calories: 250, time: 20 },
    { emoji: '🍛', name: 'Ragda Pattice', description: 'Potato patties topped with white pea curry and tangy chutneys', calories: 430, time: 35 },
    { emoji: '🫓', name: 'Onion Kulcha', description: 'Leavened bread stuffed with spiced onion filling baked in tandoor', calories: 360, time: 30 },
    { emoji: '🥘', name: 'Idli Podi', description: 'Steamed rice cakes with spiced lentil powder and sesame oil', calories: 230, time: 20 },
    { emoji: '🍳', name: 'Keema Paratha', description: 'Flatbread stuffed with spiced minced meat and herbs', calories: 450, time: 35 },
    { emoji: '🥣', name: 'Jowar Porridge', description: 'Sorghum flour porridge with milk, sugar, and ghee', calories: 240, time: 15 },
    { emoji: '🫓', name: 'Besan Cheela', description: 'Savory gram flour pancake with onions, tomatoes, and spices', calories: 270, time: 15 },
    { emoji: '🍚', name: 'Kanda Poha', description: 'Flattened rice with onions, green chilies, and turmeric', calories: 280, time: 15 },
    { emoji: '🥞', name: 'Mysore Masala Dosa', description: 'Dosa smeared with red chutney and filled with spiced potatoes', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Bonda', description: 'Deep-fried spiced potato dumplings in gram flour batter', calories: 350, time: 25 },
    { emoji: '🍛', name: 'Chana Puri', description: 'Spiced chickpea curry served with deep-fried wheat bread', calories: 470, time: 35 },
    { emoji: '🫓', name: 'Stuffed Kulcha', description: 'Leavened bread stuffed with potatoes and paneer from tandoor', calories: 400, time: 30 },
    { emoji: '🍳', name: 'Egg Uttapam', description: 'Thick rice pancake topped with beaten egg and vegetables', calories: 330, time: 20 },
    { emoji: '🥣', name: 'Suji Halwa', description: 'Sweet semolina pudding with ghee, raisins, and cashews', calories: 350, time: 20 },
    { emoji: '🫓', name: 'Tandoori Roti with Butter', description: 'Clay oven baked whole wheat bread brushed with butter', calories: 250, time: 20 },
    { emoji: '🍚', name: 'Murmura Chivda', description: 'Puffed rice mixed with peanuts, spices, and curry leaves', calories: 220, time: 10 },
    { emoji: '🥘', name: 'Dahi Vada Morning', description: 'Lentil fritters soaked in spiced yogurt with tamarind chutney', calories: 300, time: 30 },
    { emoji: '🥞', name: 'Ragi Dosa', description: 'Crispy finger millet crepe served with onion chutney', calories: 240, time: 20 },
    { emoji: '🍛', name: 'Khaman Dhokla', description: 'Steamed gram flour cake tempered with mustard seeds and green chilies', calories: 250, time: 30 },
    { emoji: '🫓', name: 'Dal Paratha', description: 'Flatbread stuffed with spiced cooked lentils and cumin', calories: 360, time: 28 },
    { emoji: '🍳', name: 'Bread Pakora', description: 'Bread slices dipped in spiced batter and deep fried', calories: 380, time: 20 },
    { emoji: '🥣', name: 'Moong Dal Halwa', description: 'Rich dessert of slow-cooked moong dal with ghee and sugar', calories: 400, time: 45 },
    { emoji: '🥘', name: 'Kuzhi Paniyaram', description: 'Sweet and savory fermented rice batter dumplings with chutney', calories: 260, time: 25 },
    { emoji: '🫓', name: 'Aloo Kulcha', description: 'Tandoor-baked leavened bread stuffed with spiced potato filling', calories: 370, time: 30 },
    { emoji: '🍚', name: 'Upma with Coconut Chutney', description: 'Savory semolina with vegetables served alongside coconut chutney', calories: 310, time: 20 },
    { emoji: '🥞', name: 'Paper Dosa', description: 'Extra thin and crispy dosa served with sambar and chutney', calories: 270, time: 20 },
    { emoji: '🍛', name: 'Vada Pav', description: 'Spiced potato fritter in a bread roll with garlic and green chutneys', calories: 400, time: 25 },
    { emoji: '🫓', name: 'Bhakri with Thecha', description: 'Thick millet bread with spicy green chili and garlic relish', calories: 290, time: 20 },
    { emoji: '🍳', name: 'Anda Paratha', description: 'Paratha cooked with a layer of beaten egg on the surface', calories: 370, time: 22 },
    { emoji: '🥘', name: 'Sabudana Vada', description: 'Crispy tapioca and peanut patties served with green chutney', calories: 310, time: 25 },
    { emoji: '🥣', name: 'Sheera', description: 'Sweet semolina pudding flavored with saffron, cardamom, and nuts', calories: 330, time: 20 },
    { emoji: '🫓', name: 'Mughlai Paratha', description: 'Rich egg-stuffed layered paratha shallow fried in ghee', calories: 480, time: 30 },
    { emoji: '🍚', name: 'Chire Doi', description: 'Bengali flattened rice soaked in sweetened thick yogurt with banana', calories: 290, time: 10 },
    { emoji: '🥞', name: 'Ghee Roast Dosa', description: 'Golden crispy dosa roasted with generous ghee on both sides', calories: 350, time: 22 },
    { emoji: '🥘', name: 'Mini Idli Sambar', description: 'Bite-sized steamed rice cakes dunked in spiced lentil soup', calories: 240, time: 25 },
    { emoji: '🍛', name: 'Dabeli', description: 'Kutchi potato filling in a bun with sweet, spicy, and tangy chutneys', calories: 350, time: 20 },
    { emoji: '🫓', name: 'Pyaaz Paratha', description: 'Flatbread with spiced onion stuffing and butter', calories: 340, time: 28 },
    { emoji: '🍛', name: 'Khamang Kakdi Thalipeeth', description: 'Multi-grain flatbread served with spiced cucumber salad', calories: 300, time: 22 },
  ],
  lunch: [
    { emoji: '🍛', name: 'Dal Tadka Rice', description: 'Yellow lentils tempered with cumin, garlic, and ghee with steamed rice', calories: 450, time: 30 },
    { emoji: '🥘', name: 'Chicken Biryani', description: 'Fragrant basmati rice layered with spiced chicken and saffron', calories: 650, time: 55 },
    { emoji: '🍛', name: 'Rajma Chawal', description: 'Kidney bean curry in tomato gravy served with steamed rice', calories: 480, time: 35 },
    { emoji: '🥘', name: 'Paneer Butter Masala Thali', description: 'Cottage cheese in rich tomato gravy with roti, rice, and salad', calories: 600, time: 45 },
    { emoji: '🍛', name: 'Chole Rice', description: 'Spiced chickpea curry served with jeera rice and pickle', calories: 500, time: 35 },
    { emoji: '🥘', name: 'Mutton Biryani', description: 'Slow-cooked mutton layered with aromatic basmati rice and spices', calories: 700, time: 60 },
    { emoji: '🍛', name: 'Sambar Rice', description: 'Mixed vegetable and lentil stew served with steamed rice', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Fish Curry Rice', description: 'Tangy Goan fish curry with coconut milk served over rice', calories: 500, time: 35 },
    { emoji: '🍛', name: 'Dal Makhani Rice', description: 'Creamy black lentils slow-cooked with butter and cream with rice', calories: 550, time: 45 },
    { emoji: '🥘', name: 'Kadai Paneer Roti', description: 'Paneer in spiced bell pepper gravy with fresh tandoori roti', calories: 520, time: 35 },
    { emoji: '🍛', name: 'Aloo Gobi Roti', description: 'Potato and cauliflower dry curry with whole wheat roti', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Egg Curry Rice', description: 'Boiled eggs in spiced onion-tomato gravy with steamed rice', calories: 480, time: 30 },
    { emoji: '🍛', name: 'Palak Paneer Roti', description: 'Cottage cheese in creamy spinach gravy with fresh roti', calories: 500, time: 35 },
    { emoji: '🥘', name: 'Veg Biryani', description: 'Fragrant basmati rice cooked with mixed vegetables and whole spices', calories: 480, time: 45 },
    { emoji: '🍛', name: 'Rasam Rice', description: 'Tangy tamarind and tomato soup served with steamed rice and papad', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Butter Chicken Rice', description: 'Tender chicken in creamy tomato sauce with jeera rice', calories: 650, time: 45 },
    { emoji: '🍛', name: 'Moong Dal Rice', description: 'Simple moong dal with turmeric and ghee tadka over rice', calories: 400, time: 25 },
    { emoji: '🥘', name: 'Prawn Curry Rice', description: 'Coastal prawn curry with coconut and kokum served with rice', calories: 520, time: 35 },
    { emoji: '🍛', name: 'Bhindi Masala Roti', description: 'Crispy okra stir-fried with onions and spices with roti', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Chicken Curry Roti', description: 'Home-style chicken curry with onion-tomato base and wheat roti', calories: 550, time: 40 },
    { emoji: '🍛', name: 'Kadhi Chawal', description: 'Yogurt-based curry with gram flour dumplings and steamed rice', calories: 440, time: 35 },
    { emoji: '🥘', name: 'Hyderabadi Biryani', description: 'Dum-cooked biryani with marinated meat and caramelized onions', calories: 680, time: 60 },
    { emoji: '🍛', name: 'Toor Dal Rice', description: 'Pigeon pea dal with tomatoes and tadka served with rice', calories: 430, time: 28 },
    { emoji: '🥘', name: 'Matar Paneer Roti', description: 'Peas and cottage cheese in spiced tomato curry with roti', calories: 510, time: 35 },
    { emoji: '🍛', name: 'Baingan Bharta Rice', description: 'Smoky roasted eggplant mash with onions served with rice', calories: 400, time: 35 },
    { emoji: '🥘', name: 'Keema Pulao', description: 'Fragrant rice cooked with spiced minced meat and whole spices', calories: 580, time: 40 },
    { emoji: '🍛', name: 'Mixed Veg Curry Roti', description: 'Seasonal vegetables in mild curry gravy with whole wheat roti', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Lucknowi Biryani', description: 'Awadhi-style dum biryani with tender meat and kewra water', calories: 660, time: 60 },
    { emoji: '🍛', name: 'Masoor Dal Rice', description: 'Red lentil dal with garlic tadka and steamed basmati rice', calories: 410, time: 25 },
    { emoji: '🥘', name: 'Paneer Tikka Masala Roti', description: 'Grilled paneer in spiced creamy gravy with buttered roti', calories: 560, time: 40 },
    { emoji: '🍛', name: 'Lauki Chana Dal', description: 'Bottle gourd cooked with split chickpeas and mild spices with rice', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Tandoori Chicken Thali', description: 'Clay oven chicken with mint chutney, naan, dal, and salad', calories: 620, time: 50 },
    { emoji: '🍛', name: 'Jeera Rice with Raita', description: 'Cumin-tempered rice with cool spiced yogurt and papad', calories: 380, time: 20 },
    { emoji: '🥘', name: 'Malai Kofta Naan', description: 'Paneer and potato dumplings in creamy curry with garlic naan', calories: 600, time: 45 },
    { emoji: '🍛', name: 'Chana Dal Rice', description: 'Split chickpea dal with cumin tadka and steamed rice', calories: 430, time: 28 },
    { emoji: '🥘', name: 'Lamb Rogan Josh Roti', description: 'Kashmiri-style lamb in aromatic red curry with fresh roti', calories: 600, time: 55 },
    { emoji: '🍛', name: 'Aloo Matar Roti', description: 'Potato and green pea curry with whole wheat roti', calories: 440, time: 30 },
    { emoji: '🥘', name: 'Egg Biryani', description: 'Spiced basmati rice with boiled eggs and caramelized onions', calories: 520, time: 40 },
    { emoji: '🍛', name: 'Khichdi with Kadhi', description: 'Rice and moong dal porridge served with spiced yogurt curry', calories: 420, time: 35 },
    { emoji: '🥘', name: 'Shahi Paneer Naan', description: 'Paneer in rich cashew and cream gravy with butter naan', calories: 620, time: 40 },
    { emoji: '🍛', name: 'Tinda Masala Roti', description: 'Apple gourd curry cooked with onions and tomatoes with roti', calories: 390, time: 30 },
    { emoji: '🥘', name: 'Chicken Chettinad Rice', description: 'Fiery South Indian chicken curry with freshly ground spices and rice', calories: 580, time: 45 },
    { emoji: '🍛', name: 'Arhar Dal Rice', description: 'Pigeon pea dal cooked with ghee, tomatoes, and cumin over rice', calories: 420, time: 28 },
    { emoji: '🥘', name: 'Paneer Bhurji Roti', description: 'Scrambled cottage cheese with peppers and spices with roti', calories: 480, time: 25 },
    { emoji: '🍛', name: 'Cabbage Poriyal Rice', description: 'South Indian stir-fried cabbage with coconut and rice', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Mutton Korma Naan', description: 'Slow-cooked mutton in rich cashew-yogurt gravy with naan', calories: 680, time: 55 },
    { emoji: '🍛', name: 'Karela Sabzi Roti', description: 'Bitter gourd stir-fried with onions and spices with roti', calories: 380, time: 30 },
    { emoji: '🥘', name: 'Chicken Saagwala Rice', description: 'Chicken cooked in spinach and mustard greens with rice', calories: 540, time: 40 },
    { emoji: '🍛', name: 'Moong Masoor Dal Rice', description: 'Mixed lentils tempered with garlic and cumin with rice', calories: 420, time: 25 },
    { emoji: '🥘', name: 'Dum Aloo Roti', description: 'Baby potatoes in rich Kashmiri-style spiced gravy with roti', calories: 480, time: 35 },
    { emoji: '🍛', name: 'Vegetable Pulao', description: 'Fragrant rice with mixed vegetables and whole spices', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Chicken Tikka Thali', description: 'Grilled chicken with dal, roti, raita, and green salad', calories: 600, time: 50 },
    { emoji: '🍛', name: 'Methi Dal Rice', description: 'Fenugreek-flavored lentils with garlic tadka and rice', calories: 410, time: 28 },
    { emoji: '🥘', name: 'Navratan Korma Naan', description: 'Nine-gem mixed vegetable curry in cream gravy with naan', calories: 560, time: 45 },
    { emoji: '🍛', name: 'Tamatar Shorba Roti', description: 'Spiced tomato soup with cumin served with crispy roti', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Fish Fry Thali', description: 'Crispy fried fish with dal, rice, salad, and lemon wedge', calories: 550, time: 40 },
    { emoji: '🍛', name: 'Urad Dal Rice', description: 'Black gram dal with ginger and green chilies with rice', calories: 440, time: 30 },
    { emoji: '🥘', name: 'Paneer Do Pyaza Roti', description: 'Paneer with double onions in spiced gravy with roti', calories: 510, time: 35 },
    { emoji: '🍛', name: 'Kootu Curry Rice', description: 'Kerala-style mixed vegetable and lentil curry with rice', calories: 420, time: 35 },
    { emoji: '🥘', name: 'Chicken Korma Naan', description: 'Mild chicken curry in yogurt and nut gravy with naan', calories: 620, time: 45 },
    { emoji: '🍛', name: 'Sev Tamatar Roti', description: 'Tangy tomato curry garnished with crispy sev with roti', calories: 400, time: 25 },
    { emoji: '🥘', name: 'Lamb Keema Roti', description: 'Spiced minced lamb cooked with peas, onions, and roti', calories: 560, time: 40 },
    { emoji: '🍛', name: 'Plain Khichdi Pickle', description: 'Simple rice and moong dal comfort meal with ghee and pickle', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Chettinad Fish Rice', description: 'South Indian spiced fish curry with curry leaves and rice', calories: 520, time: 40 },
    { emoji: '🍛', name: 'Dahi Aloo Roti', description: 'Potatoes in yogurt-based gravy with cumin and roti', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Veg Kofta Curry Roti', description: 'Mixed vegetable dumplings in spiced onion gravy with roti', calories: 500, time: 45 },
    { emoji: '🍛', name: 'Panchmel Dal Rice', description: 'Five-lentil mix cooked Rajasthani style with ghee and rice', calories: 450, time: 30 },
    { emoji: '🥘', name: 'Mutton Nihari Naan', description: 'Slow-cooked mutton stew with rich spices and garnishes with naan', calories: 690, time: 60 },
    { emoji: '🍛', name: 'Sem Ki Phali Roti', description: 'Flat beans curry with garlic and tomatoes with roti', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Egg Roast Rice', description: 'Kerala-style egg roast in coconut and spices with rice', calories: 490, time: 30 },
    { emoji: '🍛', name: 'Tomato Rice', description: 'South Indian tomato-flavored rice with peanuts and curry leaves', calories: 420, time: 25 },
    { emoji: '🥘', name: 'Palak Chicken Rice', description: 'Chicken in creamy spinach gravy served with jeera rice', calories: 560, time: 40 },
    { emoji: '🍛', name: 'Kala Chana Rice', description: 'Black chickpeas in tangy curry served with steamed rice', calories: 460, time: 35 },
    { emoji: '🥘', name: 'Paneer Lababdar Naan', description: 'Paneer in rich tomato-cream gravy with butter naan', calories: 590, time: 40 },
    { emoji: '🍛', name: 'Lemon Rice', description: 'Tangy lemon-flavored rice with peanuts, turmeric, and curry leaves', calories: 400, time: 20 },
    { emoji: '🥘', name: 'Chicken Do Pyaza Roti', description: 'Chicken cooked with double the onions in spiced curry with roti', calories: 540, time: 40 },
    { emoji: '🍛', name: 'Chana Masala Rice', description: 'Spiced chickpeas in tangy tomato gravy with basmati rice', calories: 470, time: 35 },
    { emoji: '🥘', name: 'Murg Makhani Naan', description: 'Creamy butter chicken with smoky flavor and garlic naan', calories: 640, time: 45 },
    { emoji: '🍛', name: 'Curd Rice', description: 'Cool yogurt rice with mustard seeds, curry leaves, and pomegranate', calories: 380, time: 15 },
    { emoji: '🥘', name: 'Kathal Biryani', description: 'Jackfruit biryani cooked with fragrant spices and herbs', calories: 480, time: 50 },
    { emoji: '🍛', name: 'Spinach Dal Rice', description: 'Palak dal with tempered garlic and cumin over steamed rice', calories: 410, time: 28 },
    { emoji: '🥘', name: 'Achari Chicken Roti', description: 'Chicken in tangy pickle-spice gravy with wheat roti', calories: 530, time: 40 },
    { emoji: '🍛', name: 'Coconut Rice', description: 'Rice tempered with coconut, cashews, and South Indian spices', calories: 440, time: 20 },
    { emoji: '🥘', name: 'Bhindi Do Pyaza Roti', description: 'Okra and onion stir-fry in spices with fresh roti', calories: 400, time: 30 },
    { emoji: '🍛', name: 'Tamarind Rice', description: 'South Indian tangy tamarind-flavored rice with peanuts', calories: 420, time: 25 },
    { emoji: '🥘', name: 'Chicken Vindaloo Rice', description: 'Goan spicy and tangy chicken curry with steamed rice', calories: 560, time: 45 },
    { emoji: '🍛', name: 'Mooli Sabzi Roti', description: 'Radish dry curry with cumin and green chilies with roti', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Paneer Jalfrezi Roti', description: 'Paneer stir-fried with colorful bell peppers in tangy sauce with roti', calories: 500, time: 30 },
    { emoji: '🍛', name: 'Bisibele Bath', description: 'Karnataka-style spiced rice with lentils and vegetables', calories: 460, time: 40 },
    { emoji: '🥘', name: 'Mughlai Chicken Biryani', description: 'Royal-style chicken biryani with saffron and rose water', calories: 670, time: 60 },
    { emoji: '🍛', name: 'Varan Bhaat', description: 'Simple Maharashtrian toor dal and rice with ghee', calories: 420, time: 25 },
    { emoji: '🥘', name: 'Mushroom Matar Roti', description: 'Mushroom and green pea curry in onion gravy with roti', calories: 440, time: 30 },
    { emoji: '🍛', name: 'Bagara Rice', description: 'Hyderabadi spiced rice with peanuts, sesame, and curry leaves', calories: 410, time: 25 },
    { emoji: '🥘', name: 'Lamb Biryani', description: 'Layered lamb and rice biryani with raita and salan', calories: 700, time: 60 },
    { emoji: '🍛', name: 'Gujarati Dal Rice', description: 'Sweet and tangy Gujarati-style dal with steamed rice', calories: 430, time: 28 },
    { emoji: '🥘', name: 'Mixed Dal Tadka Roti', description: 'Three-lentil mix with garlic tadka and fresh wheat roti', calories: 440, time: 30 },
    { emoji: '🍛', name: 'Vangi Bath', description: 'Karnataka-style brinjal rice with freshly ground spices', calories: 440, time: 35 },
    { emoji: '🥘', name: 'Doi Maach Rice', description: 'Bengali fish in yogurt gravy with mustard and steamed rice', calories: 530, time: 40 },
    { emoji: '🍛', name: 'Alu Posto Rice', description: 'Bengali potatoes in poppy seed paste with steamed rice', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Pindi Chole Kulcha', description: 'Dark spiced chickpeas Rawalpindi-style with tandoori kulcha', calories: 520, time: 40 },
  ],
  tea: [
    { emoji: '☕', name: 'Chai with Samosa', description: 'Hot masala chai served with crispy potato-filled pastry triangles', calories: 280, time: 30 },
    { emoji: '☕', name: 'Chai with Pakora', description: 'Ginger tea served with crispy gram flour-battered vegetable fritters', calories: 300, time: 25 },
    { emoji: '☕', name: 'Chai with Biscuits', description: 'Classic masala chai with a side of Parle-G or Bourbon biscuits', calories: 180, time: 8 },
    { emoji: '☕', name: 'Chai with Mathri', description: 'Hot tea served with flaky spiced fried crackers', calories: 250, time: 10 },
    { emoji: '☕', name: 'Chai with Rusk', description: 'Strong tea served with crispy twice-baked sweet bread', calories: 200, time: 8 },
    { emoji: '☕', name: 'Chai with Kachori', description: 'Masala chai with small moong dal stuffed fried pastry', calories: 290, time: 30 },
    { emoji: '☕', name: 'Chai with Namkeen', description: 'Milky chai served with a bowl of spicy mixed savory snacks', calories: 220, time: 8 },
    { emoji: '☕', name: 'Chai with Toast Butter', description: 'Ginger chai with crispy buttered toast slices', calories: 230, time: 10 },
    { emoji: '☕', name: 'Cutting Chai with Vada Pav', description: 'Half cup strong tea with a small potato fritter burger', calories: 300, time: 25 },
    { emoji: '☕', name: 'Chai with Bhakarvadi', description: 'Tea served with crispy spiral spiced Maharashtrian snack', calories: 250, time: 10 },
    { emoji: '🫖', name: 'Masala Chai with Cake Rusk', description: 'Spiced tea with sweet cardamom-scented cake rusk', calories: 210, time: 10 },
    { emoji: '☕', name: 'Chai with Murukku', description: 'Tea served with crispy South Indian spiral rice snack', calories: 240, time: 10 },
    { emoji: '☕', name: 'Chai with Banana Chips', description: 'Milky tea with crispy thin Kerala banana chips', calories: 260, time: 8 },
    { emoji: '☕', name: 'Adrak Chai with Maska Pav', description: 'Strong ginger tea with buttered soft bread roll', calories: 250, time: 12 },
    { emoji: '☕', name: 'Chai with Mixture', description: 'Cardamom tea with South Indian crunchy sev mixture', calories: 230, time: 8 },
    { emoji: '☕', name: 'Chai with Jalebi', description: 'Hot chai with crispy sweet saffron-soaked jalebi spirals', calories: 300, time: 30 },
    { emoji: '🫖', name: 'Green Tea with Khakhra', description: 'Light green tea with thin crispy Gujarati wheat crackers', calories: 130, time: 8 },
    { emoji: '☕', name: 'Chai with Dhokla', description: 'Tea served with steamed savory gram flour cake with chutney', calories: 220, time: 25 },
    { emoji: '☕', name: 'Irani Chai with Osmania Biscuit', description: 'Hyderabadi thick tea with crumbly butter biscuits', calories: 240, time: 10 },
    { emoji: '☕', name: 'Chai with Shakarpara', description: 'Tea with sweet diamond-shaped fried flour cookies', calories: 260, time: 10 },
    { emoji: '☕', name: 'Chai with Paneer Pakora', description: 'Hot tea with gram flour-battered fried paneer slices', calories: 290, time: 25 },
    { emoji: '☕', name: 'Chai with Bread Pakora', description: 'Masala chai with stuffed bread slices dipped in batter and fried', calories: 300, time: 25 },
    { emoji: '☕', name: 'Chai with Sev Puri', description: 'Tea alongside crispy puri topped with sev, chutneys, and onion', calories: 220, time: 15 },
    { emoji: '🫖', name: 'Kashmiri Kahwa with Badam', description: 'Saffron and almond green tea with whole spices', calories: 120, time: 12 },
    { emoji: '☕', name: 'Chai with Methi Matthi', description: 'Tea with crispy fenugreek-flavored fried crackers', calories: 240, time: 10 },
    { emoji: '☕', name: 'Chai with Suji Toast', description: 'Tea with semolina-crusted spiced toast slices', calories: 210, time: 12 },
    { emoji: '☕', name: 'Filter Coffee with Benne Biscuit', description: 'South Indian filter coffee with buttery Karnataka cookies', calories: 220, time: 10 },
    { emoji: '☕', name: 'Chai with Chivda', description: 'Hot tea with crunchy flattened rice and peanut mix', calories: 240, time: 8 },
    { emoji: '☕', name: 'Chai with Gujiya', description: 'Tea with sweet fried dumplings filled with khoya and nuts', calories: 280, time: 30 },
    { emoji: '☕', name: 'Chai with Aloo Tikki', description: 'Spiced tea with crispy golden potato patties and chutney', calories: 270, time: 25 },
    { emoji: '🫖', name: 'Masala Chai with Mathi', description: 'Traditional spiced tea with Rajasthani crispy savory cookies', calories: 230, time: 10 },
    { emoji: '☕', name: 'Chai with Moong Dal Pakoda', description: 'Tea served with crispy fried moong dal fritters', calories: 260, time: 25 },
    { emoji: '☕', name: 'Chai with Pani Puri', description: 'Hot tea with hollow puris filled with spicy tangy water', calories: 200, time: 15 },
    { emoji: '☕', name: 'Chai with Khandvi', description: 'Tea with delicate rolled gram flour and yogurt pinwheels', calories: 190, time: 30 },
    { emoji: '☕', name: 'Chai with Fafda', description: 'Tea with crispy Gujarati gram flour strips', calories: 250, time: 10 },
    { emoji: '☕', name: 'Chai with Thattai', description: 'Tea served with crispy South Indian rice flour crackers', calories: 220, time: 10 },
    { emoji: '🫖', name: 'Sulaimani Tea with Dates', description: 'Malabar-style black tea with lemon and sweet dates', calories: 150, time: 10 },
    { emoji: '☕', name: 'Chai with Chakli', description: 'Tea with crispy spiral-shaped Maharashtrian rice snack', calories: 230, time: 10 },
    { emoji: '☕', name: 'Chai with Onion Pakora', description: 'Rainy day special: hot chai with crispy onion fritters', calories: 280, time: 25 },
    { emoji: '☕', name: 'Chai with Namak Pare', description: 'Tea with small salty diamond-shaped fried flour snacks', calories: 240, time: 10 },
    { emoji: '☕', name: 'Chai with Poha Chivda', description: 'Tea served with a light flattened rice dry snack mix', calories: 210, time: 10 },
    { emoji: '☕', name: 'Chai with Batata Vada', description: 'Tea with crispy deep-fried spiced potato dumplings', calories: 280, time: 25 },
    { emoji: '🫖', name: 'Tulsi Tea with Murmura', description: 'Holy basil herbal tea with spiced puffed rice', calories: 120, time: 8 },
    { emoji: '☕', name: 'Chai with Dry Kachori', description: 'Hot tea with small crispy lentil-stuffed pastry balls', calories: 260, time: 10 },
    { emoji: '☕', name: 'Chai with Aloo Bonda', description: 'Masala tea with deep-fried potato balls in gram flour batter', calories: 290, time: 25 },
    { emoji: '☕', name: 'Chai with Bhakarwadi', description: 'Hot tea with spicy-sweet spiral rolled snack from Pune', calories: 250, time: 10 },
    { emoji: '☕', name: 'Masala Chai with Nankhatai', description: 'Spiced tea served with crumbly Indian shortbread cookies', calories: 240, time: 10 },
    { emoji: '☕', name: 'Chai with Mirchi Bajji', description: 'Tea with whole green chili fritters in gram flour batter', calories: 230, time: 20 },
    { emoji: '☕', name: 'Chai with Kaja', description: 'Tea with flaky layered sweet pastry from Andhra', calories: 270, time: 10 },
    { emoji: '☕', name: 'Chai with Murmura Chivda', description: 'Cardamom tea with spiced puffed rice and peanut snack', calories: 200, time: 8 },
    { emoji: '🫖', name: 'Rose Tea with Badam Biscuit', description: 'Rose-flavored tea with almond-topped butter cookies', calories: 190, time: 10 },
    { emoji: '☕', name: 'Chai with Dal Vada', description: 'Hot tea with crispy fried lentil patties and chutney', calories: 270, time: 25 },
    { emoji: '☕', name: 'Chai with Corn Chaat', description: 'Tea served with spiced buttered sweet corn kernels', calories: 200, time: 15 },
    { emoji: '☕', name: 'Chai with Palak Pakoda', description: 'Tea with crispy spinach fritters in spiced batter', calories: 230, time: 25 },
    { emoji: '☕', name: 'Chai with Bhel Puri', description: 'Tea alongside tangy puffed rice, sev, and chutney mix', calories: 210, time: 10 },
    { emoji: '☕', name: 'Chai with Mysore Pak', description: 'Tea with rich gram flour fudge made with ghee', calories: 280, time: 10 },
    { emoji: '☕', name: 'Chai with Papdi Chaat', description: 'Tea with crispy wafers topped with yogurt, chutneys, and sev', calories: 250, time: 15 },
    { emoji: '☕', name: 'Chai with Matar Kachori', description: 'Tea with small green pea-stuffed fried pastry', calories: 270, time: 30 },
    { emoji: '🫖', name: 'Elaichi Tea with Marie Biscuit', description: 'Cardamom-flavored tea with light crispy Marie biscuits', calories: 160, time: 8 },
    { emoji: '☕', name: 'Chai with Pyaaz Kachori', description: 'Hot tea served with crispy onion-stuffed pastry', calories: 290, time: 30 },
    { emoji: '☕', name: 'Chai with Aloo Chaat', description: 'Tea with spiced crispy potato cubes with tamarind chutney', calories: 240, time: 20 },
    { emoji: '☕', name: 'Chai with Gavvalu', description: 'Tea with small shell-shaped sweet fried Andhra snack', calories: 220, time: 10 },
    { emoji: '☕', name: 'Chai with Banana Fritters', description: 'Tea with Kerala-style ripe banana deep-fried in batter', calories: 260, time: 20 },
    { emoji: '☕', name: 'Chai with Egg Puff', description: 'Tea with flaky pastry puff filled with spiced boiled egg', calories: 280, time: 15 },
    { emoji: '☕', name: 'Chai with Chana Jor Garam', description: 'Tea with spiced flattened chickpea street snack', calories: 190, time: 8 },
    { emoji: '🫖', name: 'Lemon Ginger Tea with Almonds', description: 'Fresh lemon and ginger brew with roasted almonds', calories: 140, time: 10 },
    { emoji: '☕', name: 'Chai with Veg Puff', description: 'Tea with flaky pastry stuffed with spiced mixed vegetables', calories: 260, time: 15 },
    { emoji: '☕', name: 'Chai with Karanji', description: 'Tea with crescent-shaped sweet fried dumplings with coconut', calories: 270, time: 30 },
    { emoji: '☕', name: 'Chai with Ribbon Pakoda', description: 'Tea served with thin crispy ribbon-shaped rice flour snack', calories: 220, time: 10 },
    { emoji: '☕', name: 'Chai with Samosa Chaat', description: 'Tea with crushed samosa topped with chickpeas and chutneys', calories: 300, time: 30 },
    { emoji: '☕', name: 'Filter Coffee with Murukku', description: 'Strong South Indian coffee with crunchy spiral rice snack', calories: 230, time: 10 },
    { emoji: '☕', name: 'Chai with Dahi Puri', description: 'Tea with hollow puris filled with yogurt and sweet chutney', calories: 200, time: 15 },
    { emoji: '☕', name: 'Chai with Kuzhalappam', description: 'Tea with crispy rolled Kerala rice flour tubes', calories: 210, time: 10 },
    { emoji: '☕', name: 'Masala Chai with Matthi', description: 'Strong masala tea with salted flaky fried wheat crackers', calories: 240, time: 10 },
    { emoji: '🫖', name: 'Saffron Milk with Dry Fruits', description: 'Warm saffron milk with pistachios, almonds, and cashews', calories: 200, time: 10 },
    { emoji: '☕', name: 'Chai with Gulab Jamun', description: 'Hot chai with soft milk-solid dumplings in sugar syrup', calories: 300, time: 15 },
    { emoji: '☕', name: 'Chai with Chana Chaat', description: 'Tea with spiced boiled chickpeas, onion, and lemon', calories: 200, time: 12 },
    { emoji: '☕', name: 'Chai with Soan Papdi', description: 'Tea with flaky layered sweet made from gram flour and sugar', calories: 250, time: 8 },
    { emoji: '☕', name: 'Chai with Murmura Bhel', description: 'Tea with quick puffed rice, onion, and chutney snack', calories: 180, time: 8 },
    { emoji: '☕', name: 'Chai with Masala Peanuts', description: 'Masala tea with crunchy spice-coated fried peanuts', calories: 240, time: 15 },
    { emoji: '☕', name: 'Chai with Methi Pakoda', description: 'Tea served with crispy fenugreek leaf fritters', calories: 230, time: 25 },
    { emoji: '☕', name: 'Chai with Rasgulla', description: 'Hot tea with soft spongy cottage cheese balls in syrup', calories: 250, time: 10 },
    { emoji: '☕', name: 'Chai with Khasta Kachori', description: 'Tea with flaky crispy lentil-stuffed pastry rounds', calories: 280, time: 30 },
    { emoji: '🫖', name: 'Masala Doodh with Kesar', description: 'Warm spiced milk with saffron, turmeric, and almonds', calories: 180, time: 10 },
    { emoji: '☕', name: 'Chai with Dry Samosa', description: 'Tea with small crunchy cocktail-sized samosas', calories: 220, time: 10 },
    { emoji: '☕', name: 'Chai with Sweet Boondi', description: 'Tea with tiny sweet gram flour droplets soaked in syrup', calories: 230, time: 8 },
    { emoji: '☕', name: 'Chai with Maddur Vada', description: 'Tea with crispy Karnataka-style onion and rice flour fritter', calories: 250, time: 20 },
    { emoji: '☕', name: 'Chai with Nimki', description: 'Tea with small crispy diamond-shaped fried savory pastry', calories: 220, time: 10 },
    { emoji: '☕', name: 'Chai with Shakkar Pare', description: 'Tea served with small sweet fried dough diamonds', calories: 260, time: 10 },
    { emoji: '☕', name: 'Chai with Dahi Bhalla', description: 'Tea with lentil dumplings in spiced yogurt with chutney', calories: 240, time: 25 },
    { emoji: '☕', name: 'Chai with Moong Dal Namkeen', description: 'Tea with crispy fried seasoned split moong dal', calories: 200, time: 8 },
    { emoji: '🫖', name: 'Badam Milk with Pista', description: 'Warm almond milk drink garnished with slivered pistachios', calories: 190, time: 10 },
    { emoji: '☕', name: 'Chai with Til Chikki', description: 'Tea with crunchy sesame and jaggery brittle', calories: 210, time: 8 },
    { emoji: '☕', name: 'Chai with Bombay Sandwich', description: 'Tea with layered vegetable sandwich with green chutney', calories: 250, time: 15 },
    { emoji: '☕', name: 'Chai with Peanut Chikki', description: 'Hot masala tea with crunchy peanut and jaggery brittle', calories: 230, time: 8 },
    { emoji: '☕', name: 'Chai with Meetha Gujiya', description: 'Tea with sweet fried dumplings filled with semolina and coconut', calories: 280, time: 30 },
    { emoji: '☕', name: 'Chai with Masala Papad', description: 'Tea with crispy roasted papad topped with onion and tomato', calories: 150, time: 8 },
    { emoji: '☕', name: 'Filter Coffee with Kodubale', description: 'Strong coffee with crunchy ring-shaped Karnataka rice snack', calories: 220, time: 10 },
    { emoji: '☕', name: 'Chai with Kalakand', description: 'Masala tea with soft milk cake sweetened with sugar', calories: 260, time: 10 },
    { emoji: '🫖', name: 'Haldi Doodh with Makhana', description: 'Warm turmeric milk with roasted lotus seed puffs', calories: 160, time: 10 },
  ],
  dinner: [
    { emoji: '🍛', name: 'Roti Sabzi Thali', description: 'Whole wheat roti with seasonal vegetable curry, dal, and salad', calories: 480, time: 35 },
    { emoji: '🥘', name: 'Chicken Curry Roti', description: 'Home-style chicken curry with fresh whole wheat roti', calories: 550, time: 40 },
    { emoji: '🍛', name: 'Dal Fry Roti', description: 'Tempered yellow lentils with garlic and cumin with roti', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Paneer Tikka Masala Naan', description: 'Grilled paneer in spiced creamy tomato gravy with naan', calories: 580, time: 40 },
    { emoji: '🍛', name: 'Aloo Gobi Roti', description: 'Dry potato and cauliflower curry with whole wheat chapati', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Butter Chicken Naan', description: 'Tender chicken in buttery tomato cream sauce with garlic naan', calories: 680, time: 45 },
    { emoji: '🍛', name: 'Bhindi Fry Roti', description: 'Crispy okra stir-fried with onions and spices with roti', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Fish Curry Rice', description: 'Tangy coastal fish curry with coconut and steamed rice', calories: 520, time: 35 },
    { emoji: '🍛', name: 'Palak Paneer Roti', description: 'Cottage cheese cubes in creamy spinach gravy with roti', calories: 500, time: 35 },
    { emoji: '🥘', name: 'Mutton Curry Roti', description: 'Slow-cooked mutton in rich onion-tomato gravy with roti', calories: 600, time: 55 },
    { emoji: '🍛', name: 'Rajma Roti', description: 'Kidney bean curry in thick tomato gravy with chapati', calories: 460, time: 35 },
    { emoji: '🥘', name: 'Chicken Biryani', description: 'Aromatic basmati rice layered with spiced chicken and herbs', calories: 650, time: 55 },
    { emoji: '🍛', name: 'Baingan Bharta Roti', description: 'Smoky mashed eggplant with onions and tomatoes with roti', calories: 420, time: 35 },
    { emoji: '🥘', name: 'Egg Curry Roti', description: 'Hard-boiled eggs in spiced onion-tomato gravy with roti', calories: 470, time: 30 },
    { emoji: '🍛', name: 'Kadhi Pakora Rice', description: 'Yogurt-gram flour curry with fritters served with rice', calories: 480, time: 35 },
    { emoji: '🥘', name: 'Keema Matar Roti', description: 'Spiced minced meat with green peas served with roti', calories: 550, time: 40 },
    { emoji: '🍛', name: 'Toor Dal Rice', description: 'Pigeon pea lentils with tomato tadka and steamed rice', calories: 440, time: 28 },
    { emoji: '🥘', name: 'Paneer Butter Masala Roti', description: 'Cottage cheese in rich creamy tomato gravy with butter roti', calories: 560, time: 40 },
    { emoji: '🍛', name: 'Mixed Veg Curry Roti', description: 'Medley of seasonal vegetables in light curry with roti', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Tandoori Chicken Roti', description: 'Smoky clay-oven chicken with mint chutney and roti', calories: 530, time: 45 },
    { emoji: '🍛', name: 'Chana Masala Roti', description: 'Spiced chickpeas in tangy tomato gravy with chapati', calories: 460, time: 35 },
    { emoji: '🥘', name: 'Prawn Masala Rice', description: 'Coastal prawns in spiced coconut gravy with steamed rice', calories: 540, time: 35 },
    { emoji: '🍛', name: 'Lauki Ki Sabzi Roti', description: 'Bottle gourd cooked with tomatoes and mild spices with roti', calories: 380, time: 30 },
    { emoji: '🥘', name: 'Lamb Rogan Josh Naan', description: 'Kashmiri lamb in aromatic red chili and yogurt curry with naan', calories: 640, time: 55 },
    { emoji: '🍛', name: 'Moong Dal Roti', description: 'Simple moong lentils with ghee tadka and fresh chapati', calories: 410, time: 25 },
    { emoji: '🥘', name: 'Chicken Tikka Roti', description: 'Grilled spiced chicken pieces served with roti and chutney', calories: 500, time: 40 },
    { emoji: '🍛', name: 'Aloo Matar Roti', description: 'Potato and green pea curry in light gravy with roti', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Mutton Biryani', description: 'Slow-cooked lamb layered with saffron rice and fried onions', calories: 700, time: 60 },
    { emoji: '🍛', name: 'Karela Sabzi Roti', description: 'Stuffed bitter gourd with onion masala and chapati', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Shahi Paneer Naan', description: 'Paneer in cashew and saffron cream gravy with naan', calories: 600, time: 40 },
    { emoji: '🍛', name: 'Tinda Masala Roti', description: 'Apple gourd in onion-tomato gravy with fresh roti', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Chicken Saag Roti', description: 'Chicken in mustard greens and spinach sauce with roti', calories: 520, time: 40 },
    { emoji: '🍛', name: 'Dal Makhani Roti', description: 'Creamy slow-cooked black lentils with butter and wheat roti', calories: 500, time: 45 },
    { emoji: '🥘', name: 'Fish Fry Rice', description: 'Crispy masala-fried fish served with jeera rice and lemon', calories: 540, time: 35 },
    { emoji: '🍛', name: 'Gobhi Matar Roti', description: 'Cauliflower and peas in tomato gravy with chapati', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Mughlai Chicken Naan', description: 'Rich creamy chicken curry with almonds and butter naan', calories: 650, time: 50 },
    { emoji: '🍛', name: 'Masoor Dal Roti', description: 'Red lentil dal with garlic and cumin tadka with roti', calories: 420, time: 25 },
    { emoji: '🥘', name: 'Egg Biryani', description: 'Fragrant basmati rice with spiced boiled eggs and herbs', calories: 500, time: 40 },
    { emoji: '🍛', name: 'Methi Aloo Roti', description: 'Fenugreek leaves and potato dry curry with roti', calories: 410, time: 30 },
    { emoji: '🥘', name: 'Kadai Chicken Roti', description: 'Chicken in bell pepper and tomato kadai masala with roti', calories: 540, time: 40 },
    { emoji: '🍛', name: 'Sem Ki Phali Roti', description: 'Flat beans cooked with garlic and onions with chapati', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Paneer Do Pyaza Roti', description: 'Paneer with generous onions in spiced gravy with roti', calories: 520, time: 35 },
    { emoji: '🍛', name: 'Matar Mushroom Roti', description: 'Green peas and mushroom curry in tomato gravy with roti', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Chicken Korma Naan', description: 'Mild chicken in yogurt and cashew cream sauce with naan', calories: 620, time: 45 },
    { emoji: '🍛', name: 'Urad Dal Roti', description: 'Black gram dal slow-cooked with ginger and spices with roti', calories: 440, time: 30 },
    { emoji: '🥘', name: 'Lamb Keema Roti', description: 'Minced lamb with peas in aromatic spices with chapati', calories: 570, time: 40 },
    { emoji: '🍛', name: 'Cabbage Poriyal Rice', description: 'Stir-fried cabbage with coconut and curry leaves with rice', calories: 400, time: 25 },
    { emoji: '🥘', name: 'Dum Aloo Roti', description: 'Baby potatoes in rich Kashmiri gravy with fresh roti', calories: 470, time: 35 },
    { emoji: '🍛', name: 'Arhar Dal Roti', description: 'Pigeon pea lentils with cumin and tomato tadka with roti', calories: 420, time: 28 },
    { emoji: '🥘', name: 'Chicken Vindaloo Rice', description: 'Goan spicy tangy chicken curry served with steamed rice', calories: 560, time: 45 },
    { emoji: '🍛', name: 'Sev Tamatar Roti', description: 'Tangy tomato curry with crispy sev topping and roti', calories: 410, time: 25 },
    { emoji: '🥘', name: 'Malai Kofta Naan', description: 'Paneer and potato dumplings in cashew cream curry with naan', calories: 600, time: 45 },
    { emoji: '🍛', name: 'Parwal Sabzi Roti', description: 'Pointed gourd curry with onion and tomato with chapati', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Achari Mutton Roti', description: 'Mutton in pickle-spiced tangy gravy with whole wheat roti', calories: 580, time: 50 },
    { emoji: '🍛', name: 'Palak Dal Roti', description: 'Spinach and lentil curry with garlic tadka and roti', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Chettinad Chicken Rice', description: 'Fiery South Indian chicken with freshly ground spices and rice', calories: 560, time: 45 },
    { emoji: '🍛', name: 'Dahi Aloo Roti', description: 'Potatoes in tangy yogurt gravy with cumin and roti', calories: 430, time: 30 },
    { emoji: '🥘', name: 'Veg Biryani', description: 'Layered vegetable rice with aromatic spices and raita', calories: 480, time: 45 },
    { emoji: '🍛', name: 'Pyaaz Tamatar Sabzi Roti', description: 'Onion and tomato curry with simple spices and chapati', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Chicken Handi Roti', description: 'Chicken slow-cooked in clay pot with tomatoes and cream with roti', calories: 540, time: 45 },
    { emoji: '🍛', name: 'Panchmel Dal Roti', description: 'Rajasthani five-lentil mix with ghee and roti', calories: 450, time: 30 },
    { emoji: '🥘', name: 'Navratan Korma Naan', description: 'Nine-jewel mixed vegetable curry in cream with naan', calories: 560, time: 45 },
    { emoji: '🍛', name: 'Shimla Mirch Sabzi Roti', description: 'Bell pepper and potato stir-fry with cumin and roti', calories: 400, time: 25 },
    { emoji: '🥘', name: 'Doi Maach Rice', description: 'Bengali fish in mustard yogurt curry with steamed rice', calories: 530, time: 40 },
    { emoji: '🍛', name: 'Chana Dal Roti', description: 'Split chickpea lentils with cumin tadka and chapati', calories: 430, time: 28 },
    { emoji: '🥘', name: 'Paneer Jalfrezi Roti', description: 'Paneer with bell peppers in tangy tomato sauce with roti', calories: 500, time: 30 },
    { emoji: '🍛', name: 'Mooli Sabzi Roti', description: 'Radish curry cooked with tomato and mild spices with roti', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Mutton Korma Naan', description: 'Rich mutton in cashew-yogurt gravy with butter naan', calories: 670, time: 55 },
    { emoji: '🍛', name: 'Khichdi Dal', description: 'Comfort rice and moong dal porridge with ghee and papad', calories: 400, time: 25 },
    { emoji: '🥘', name: 'Chicken Malai Tikka Roti', description: 'Creamy grilled chicken with cheese and roti', calories: 530, time: 40 },
    { emoji: '🍛', name: 'Gajar Matar Roti', description: 'Carrot and green peas dry curry with cumin and roti', calories: 400, time: 25 },
    { emoji: '🥘', name: 'Hyderabadi Biryani', description: 'Dum-cooked layered meat biryani with mirchi ka salan', calories: 680, time: 60 },
    { emoji: '🍛', name: 'Methi Dal Roti', description: 'Fenugreek-flavored lentils with garlic tadka and roti', calories: 420, time: 28 },
    { emoji: '🥘', name: 'Matar Paneer Roti', description: 'Peas and paneer in mildly spiced tomato curry with roti', calories: 510, time: 35 },
    { emoji: '🍛', name: 'Kootu Curry Rice', description: 'Kerala mixed vegetables and lentils in coconut with rice', calories: 440, time: 35 },
    { emoji: '🥘', name: 'Lamb Nihari Naan', description: 'Slow-braised lamb shank stew with naan and garnishes', calories: 700, time: 60 },
    { emoji: '🍛', name: 'Tamatar Ki Sabzi Roti', description: 'Simple tomato curry with cumin and turmeric with chapati', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Chicken Rezala Paratha', description: 'Bengali mild chicken in white gravy with flaky paratha', calories: 590, time: 45 },
    { emoji: '🍛', name: 'Gujarati Dal Rice', description: 'Sweet and sour Gujarati-style lentils with steamed rice', calories: 430, time: 28 },
    { emoji: '🥘', name: 'Bhuna Gosht Roti', description: 'Dry roasted mutton with aromatic spices and fresh roti', calories: 560, time: 50 },
    { emoji: '🍛', name: 'Torai Sabzi Roti', description: 'Ridge gourd cooked with onion and light spices with chapati', calories: 380, time: 25 },
    { emoji: '🥘', name: 'Kadai Paneer Roti', description: 'Paneer and bell peppers in kadai masala with fresh roti', calories: 520, time: 35 },
    { emoji: '🍛', name: 'Plain Roti Sabzi', description: 'Simple seasonal vegetable curry with fresh chapati and pickle', calories: 400, time: 30 },
    { emoji: '🥘', name: 'Chicken Curry Rice', description: 'Classic Indian chicken curry served with steamed basmati rice', calories: 560, time: 40 },
    { emoji: '🍛', name: 'Masoor Dal Rice', description: 'Red lentil dal with tomato and garlic with steamed rice', calories: 430, time: 25 },
    { emoji: '🥘', name: 'Mushroom Masala Roti', description: 'Mushrooms in spiced onion-tomato gravy with fresh roti', calories: 440, time: 30 },
    { emoji: '🍛', name: 'Palak Aloo Roti', description: 'Spinach and potato curry with cumin and garlic with roti', calories: 420, time: 30 },
    { emoji: '🥘', name: 'Egg Roast Parotta', description: 'Kerala egg roast with flaky layered Malabar parotta', calories: 530, time: 35 },
    { emoji: '🍛', name: 'Curd Rice', description: 'Cool yogurt rice with tempering of mustard and curry leaves', calories: 400, time: 15 },
    { emoji: '🥘', name: 'Lucknowi Biryani', description: 'Awadhi-style dum biryani with kewra water and saffron', calories: 660, time: 60 },
    { emoji: '🍛', name: 'Bharwa Bhindi Roti', description: 'Stuffed okra with ground spices and peanuts with roti', calories: 420, time: 35 },
    { emoji: '🥘', name: 'Paneer Makhani Naan', description: 'Paneer in velvety butter-tomato gravy with garlic naan', calories: 590, time: 40 },
    { emoji: '🍛', name: 'Sambar Rice', description: 'Mixed vegetable lentil stew served with steamed rice', calories: 440, time: 30 },
    { emoji: '🥘', name: 'Prawn Biryani', description: 'Fragrant rice layered with spiced coastal prawns and herbs', calories: 550, time: 50 },
    { emoji: '🍛', name: 'Turai Chana Dal Roti', description: 'Ridge gourd with split chickpeas in light curry with roti', calories: 410, time: 30 },
    { emoji: '🥘', name: 'Mutton Rogan Josh Roti', description: 'Kashmiri lamb in deep red aromatic curry with chapati', calories: 600, time: 55 },
    { emoji: '🍛', name: 'Jeera Aloo Roti', description: 'Cumin-tempered potatoes with turmeric and green chilies with roti', calories: 420, time: 25 },
    { emoji: '🥘', name: 'Paneer Korma Naan', description: 'Paneer in mild nut-based cream gravy with butter naan', calories: 580, time: 40 },
    { emoji: '🍛', name: 'Vendakkai Poriyal Rice', description: 'Tamil-style okra stir-fry with coconut and steamed rice', calories: 410, time: 25 },
    { emoji: '🥘', name: 'Chicken Kali Mirch Roti', description: 'Chicken in black pepper and onion gravy with fresh roti', calories: 540, time: 40 },
  ],
}

function shuffle(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

function getPool(mealType, exclude = []) {
  let pool = MEALS_DB[mealType].filter(m => !exclude.includes(m.name))
  if (pool.length === 0) pool = MEALS_DB[mealType]
  return pool
}

function pickBestCombo(pools, dailyTarget) {
  const closeTolerance = dailyTarget * 0.02
  const goodCombos = []
  let bestCombo = null
  let bestDiff = Infinity

  const bPool = shuffle(pools.breakfast)
  const lPool = shuffle(pools.lunch)
  const tPool = shuffle(pools.tea)
  const dPool = shuffle(pools.dinner)

  const SAMPLES = 50000
  for (let i = 0; i < SAMPLES; i++) {
    const b = bPool[Math.floor(Math.random() * bPool.length)]
    const l = lPool[Math.floor(Math.random() * lPool.length)]
    const t = tPool[Math.floor(Math.random() * tPool.length)]
    const d = dPool[Math.floor(Math.random() * dPool.length)]

    const total = b.calories + l.calories + t.calories + d.calories
    const diff = Math.abs(total - dailyTarget)

    if (diff <= closeTolerance) {
      goodCombos.push({ breakfast: b, lunch: l, tea: t, dinner: d })
      if (goodCombos.length >= 50) break
    }
    if (diff < bestDiff) {
      bestDiff = diff
      bestCombo = { breakfast: b, lunch: l, tea: t, dinner: d }
    }
  }

  if (goodCombos.length > 0) {
    return goodCombos[Math.floor(Math.random() * goodCombos.length)]
  }
  return bestCombo
}

export function generatePlan(calorieTarget) {
  const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

  if (!calorieTarget) {
    // No target — just shuffle and assign
    const breakfasts = shuffle(getPool('breakfast'))
    const lunches = shuffle(getPool('lunch'))
    const teas = shuffle(getPool('tea'))
    const dinners = shuffle(getPool('dinner'))
    return {
      days: DAYS.map((day, i) => ({
        day,
        meals: {
          breakfast: { ...breakfasts[i % breakfasts.length] },
          lunch: { ...lunches[i % lunches.length] },
          tea: { ...teas[i % teas.length] },
          dinner: { ...dinners[i % dinners.length] },
        },
      })),
    }
  }

  // With calorie target — pick combos that hit the daily goal
  const pools = {
    breakfast: getPool('breakfast'),
    lunch: getPool('lunch'),
    tea: getPool('tea'),
    dinner: getPool('dinner'),
  }

  const days = DAYS.map(day => {
    const combo = pickBestCombo(pools, calorieTarget)
    return {
      day,
      meals: {
        breakfast: { ...combo.breakfast },
        lunch: { ...combo.lunch },
        tea: { ...combo.tea },
        dinner: { ...combo.dinner },
      },
    }
  })

  return { days }
}

export function regenerateMeal(mealType, currentMealName, calorieTarget) {
  let pool = getPool(mealType, [currentMealName])

  if (calorieTarget) {
    const perMealBudget = Math.round(calorieTarget / 4)
    const tolerance = perMealBudget * 0.15
    const filtered = pool.filter(m => Math.abs(m.calories - perMealBudget) <= tolerance)
    if (filtered.length > 0) pool = filtered
  }

  const picked = shuffle(pool)[0]
  return { ...picked }
}
